- name: Create postgres volume
  docker_volume:
    name: "apteka-postgres-volume"

- name: Run postgres
  docker_container:
    name: "apteka-postgres-{{ inventory_hostname }}"
    hostname: "apteka-postgres-{{ inventory_hostname }}"
    image: "postgres:{{ postgres_version }}"
    state: started
    volumes:
      - "apteka-postgres-volume:/var/lib/postgresql/data"
    ports:
      - "{{ postgres_port }}:5432"
    env:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"

- name: Sleep for 3 seconds, wait create postgres
  wait_for: timeout=3

- name: Create database
  postgresql_db:
    name: apteka
    port: "{{ postgres_port }}"
    login_host: "{{ postgres_host }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
