- name: Run apteka-auth services
  docker_service:
    project_name: apteka-auth
    definition:
      version: '3'
      services:
        web:
          container_name: apteka-auth-nginx
          image: apteka-nginx
          hostname: "apteka-auth-nginx-{{ inventory_hostname }}"
          ports:
            - "{{ apteka_auth_port }}:80"
          volumes:
            - "{{ apteka_app_root_path }}/auth:/app"
          links:
            - php
        php:
          container_name: apteka-auth-php-fpm
          image: apteka-php-fpm
          hostname: "apteka-php-fpm-{{ inventory_hostname }}"
          volumes:
            - "{{ apteka_app_root_path }}/auth:/app"