- name: Create project folder
  file:
    path: "{{ apteka_app_root_path }}"
    state: directory
    mode: 0755

- name: Build  apteka-php-fpm image
  docker_image:
     path: "{{ playbook_dir }}/dockerfiles/apteka-php-fpm"
     name: apteka-php-fpm

- name: Build  apteka-nginx image
  docker_image:
     path: "{{ playbook_dir }}/dockerfiles/apteka-nginx"
     name: apteka-nginx