- name: Build  apteka-php-fpm image
  docker_image:
     path: "{{ playbook_dir }}/dockerfiles/apteka-php-fpm"
     name: apteka-php-fpm
     force: "{{ docker_rebuild }}"

- name: Build  apteka-nginx image
  docker_image:
     path: "{{ playbook_dir }}/dockerfiles/apteka-nginx"
     name: apteka-nginx
     force: "{{ docker_rebuild }}"
